import { StyleSheet as RNStyleSheet } from 'react-native'

export const styles = RNStyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f2f2f7',
  },
  scrollContent: {
    paddingTop: 8,
    paddingBottom: 16,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerActionButton: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  headerMenuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.12)',
  },
  headerMenuCard: {
    position: 'absolute',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  headerMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
  },
  headerMenuItemBorder: {
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
  },
  headerMenuItemLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  headerMenuItemLabelDestructive: {
    color: '#dc2626',
  },
  headerTextButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  headerTextButtonLabel: {
    color: '#111827',
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1f2937',
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  detailSection: {
    marginHorizontal: 16,
    marginBottom: 18,
  },
  detailSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6b7280',
    letterSpacing: 0.4,
  },
  detailSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  detailSectionBody: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
  },
  detailSectionContent: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  pillActive: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  pillInactive: {
    backgroundColor: '#ffffff',
    borderColor: '#d1d5db',
  },
  pillActiveText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  pillInactiveText: {
    color: '#374151',
    fontWeight: '500',
  },
  rowCard: {
    backgroundColor: '#ffffff',
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#d1d5db',
  },
  rowCardLast: {
    borderBottomWidth: 0,
  },
  linkedAccountsDisclosureButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  linkedAccountsDisclosureButtonExpanded: {
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#d1d5db',
  },
  linkedAccountsDisclosureSummary: {
    flex: 1,
    gap: 10,
  },
  linkedAccountsSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  linkedAccountsSummaryBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  rowMainPressable: {
    flex: 1,
  },
  rowMainContent: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  rowMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 48,
  },
  anyImageSummary: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: '#e5e7eb',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  anyImageRow: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: '#e5e7eb',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  anyImageHeader: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: '#e5e7eb',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  anyImageTextSummary: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  anyImageTextRow: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  anyImageTextHeader: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
  },
  anyImageToneCrimson: {
    backgroundColor: '#9a031e',
  },
  anyImageToneGray: {
    backgroundColor: '#6b7280',
  },
  anyImageToneTeal: {
    backgroundColor: '#0f4c5c',
  },
  anyImageToneGreen: {
    backgroundColor: '#34c759',
  },
  anyImageToneRed: {
    backgroundColor: '#ff3b30',
  },
  rowTextContainer: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  rowTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  rowTrailing: {
    alignItems: 'flex-end',
    flexShrink: 1,
    gap: 8,
    marginLeft: 8,
    maxWidth: '42%',
    minWidth: 0,
  },
  rowValue: {
    fontSize: 14,
    color: '#4b5563',
    fontWeight: '500',
    textAlign: 'right',
  },
  rowBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  rowSwipeActions: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  rowSwipeActionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 86,
    paddingHorizontal: 12,
  },
  rowSwipeActionLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  rowSwipeActionDanger: {
    backgroundColor: '#ef4444',
  },
  rowSwipeActionNeutral: {
    backgroundColor: '#64748b',
  },
  rowSwipeActionSuccess: {
    backgroundColor: '#16a34a',
  },
  emptyText: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    color: '#6b7280',
    fontSize: 14,
  },
  sectionLoadingState: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 10,
  },
  sectionEmptyState: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 8,
  },
  sectionEmptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  sectionEmptyMessage: {
    fontSize: 14,
    lineHeight: 20,
    color: '#6b7280',
    textAlign: 'center',
  },
  loadingStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 10,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  groupTitle: {
    fontSize: 13,
    color: '#6b7280',
    fontWeight: '600',
  },
  keyValueContainer: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    backgroundColor: '#ffffff',
  },
  keyValueRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#d1d5db',
  },
  keyValuePath: {
    fontSize: 12,
    color: '#6b7280',
    fontWeight: '600',
  },
  keyValueValue: {
    marginTop: 4,
    fontSize: 13,
    color: '#111827',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    padding: 16,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  modalScroll: {
    marginTop: 12,
    marginBottom: 12,
  },
  modalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  modalRowLabel: {
    fontSize: 14,
    color: '#111827',
  },
  onboardingContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  onboardingBackdropImage: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    opacity: 0.28,
  },
  onboardingBackdropOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.66)',
  },
  onboardingContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  onboardingTitleBlock: {
    alignItems: 'center',
  },
  onboardingHeading: {
    fontSize: 32,
    fontWeight: '800',
    color: '#d1d5db',
    textAlign: 'center',
  },
  onboardingProduct: {
    marginTop: 6,
    fontSize: 50,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
  },
  onboardingCaption: {
    marginTop: 12,
    fontSize: 16,
    lineHeight: 22,
    color: '#d1d5db',
    textAlign: 'center',
  },
  onboardingCarouselWrapper: {
    flex: 1,
    justifyContent: 'center',
  },
  onboardingCarouselContent: {
    paddingVertical: 24,
    paddingHorizontal: 24,
    gap: 30,
  },
  onboardingCard: {
    width: 219,
    height: 475,
    borderRadius: 36,
    overflow: 'hidden',
    backgroundColor: '#111827',
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 5 },
  },
  onboardingCardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  onboardingFooter: {
    paddingBottom: 24,
  },
  onboardingCtaButton: {
    alignSelf: 'center',
    minWidth: 156,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 14,
  },
  onboardingCtaLabel: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '700',
  },
  input: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#111827',
    backgroundColor: '#ffffff',
  },
  searchSection: {
    marginTop: 12,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 16,
    color: '#111827',
    backgroundColor: '#ffffff',
  },
  inputText: {
    fontSize: 14,
    color: '#111827',
  },
  inputPlaceholderText: {
    fontSize: 14,
    color: '#9ca3af',
  },
  primaryButton: {
    marginHorizontal: 16,
    marginVertical: 12,
    borderRadius: 10,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 15,
  },
  secondaryButton: {
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#ffffff',
  },
  secondaryButtonText: {
    color: '#111827',
    fontWeight: '700',
    fontSize: 15,
  },
  destructiveButton: {
    borderColor: '#ef4444',
  },
  destructiveButtonText: {
    color: '#b91c1c',
  },
  editorCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  editorTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0f172a',
  },
  editorHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingBottom: 12,
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
  },
  horizontalPills: {
    marginBottom: 8,
  },
  editorGroup: {
    marginTop: 6,
    gap: 6,
  },
  quoteFormSectionTitle: {
    marginTop: 12,
    marginBottom: 2,
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  quoteFormSubsection: {
    gap: 6,
  },
  quoteFormRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 44,
    paddingVertical: 4,
  },
  quoteFormLabel: {
    flexShrink: 0,
    minWidth: 112,
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  quoteFormTextInput: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#111827',
    backgroundColor: '#ffffff',
    textAlign: 'right',
  },
  quoteFormPickerButton: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
  },
  quoteFormDateTimeControls: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  quoteFormDateTimeControl: {
    minWidth: 0,
  },
  quoteFormValue: {
    minWidth: 0,
    flexShrink: 1,
    fontSize: 15,
    color: '#111827',
    textAlign: 'right',
  },
  quoteFormPlaceholder: {
    minWidth: 0,
    flexShrink: 1,
    fontSize: 15,
    color: '#9ca3af',
    textAlign: 'right',
  },
  quoteFormCoordinateFields: {
    flex: 1,
    flexDirection: 'row',
    gap: 8,
  },
  quoteFormCoordinatesButton: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
  },
  quoteFormCoordinatesModalScreen: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  quoteFormCoordinatesModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#d1d5db',
  },
  quoteFormCoordinatesModalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
  },
  quoteFormCoordinatesMap: {
    flex: 1,
  },
  quoteFormCoordinatesMapContainer: {
    flex: 1,
  },
  quoteFormCoordinatesCenterMarker: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -15,
    marginTop: -30,
  },
  quoteFormCoordinatesLoadingBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quoteFormCoordinatesMapFallback: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    gap: 8,
    backgroundColor: '#f8fafc',
  },
  quoteFormCoordinatesMapFallbackTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  quoteFormCoordinatesMapFallbackMessage: {
    fontSize: 14,
    lineHeight: 20,
    color: '#6b7280',
    textAlign: 'center',
  },
  quoteFormCoordinateInput: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#111827',
    backgroundColor: '#ffffff',
    textAlign: 'right',
  },
  badgeChip: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeChipLabel: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 11,
  },
  badgeToneBlack: {
    backgroundColor: '#000000',
  },
  badgeToneBlue: {
    backgroundColor: '#007AFF',
  },
  badgeToneBrown: {
    backgroundColor: '#A2845E',
  },
  badgeToneCrimson: {
    backgroundColor: '#9a031e',
  },
  badgeToneCyan: {
    backgroundColor: '#32ADE6',
  },
  badgeToneGray: {
    backgroundColor: '#8E8E93',
  },
  badgeToneGreen: {
    backgroundColor: '#34C759',
  },
  badgeTonePurple: {
    backgroundColor: '#AF52DE',
  },
  badgeToneMaroon: {
    backgroundColor: '#5f0f40',
  },
  badgeToneOrange: {
    backgroundColor: '#e36414',
  },
  badgeToneRed: {
    backgroundColor: '#FF3B30',
  },
  badgeToneTeal: {
    backgroundColor: '#0f4c5c',
  },
  badgeToneYellow: {
    backgroundColor: '#FFCC00',
  },
  infoHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    gap: 16,
  },
  infoHeaderContent: {
    flex: 1,
    minWidth: 0,
  },
  infoHeaderTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  infoHeaderBadges: {
    marginTop: 6,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  infoRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: RNStyleSheet.hairlineWidth,
    borderBottomColor: '#e5e7eb',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  infoRowTextContainer: {
    flex: 1,
  },
  infoRowTitle: {
    fontSize: 12,
    color: '#6b7280',
    fontWeight: '600',
  },
  infoRowValue: {
    marginTop: 3,
    fontSize: 15,
    color: '#111827',
    fontWeight: '500',
  },
  infoRowCopyButton: {
    padding: 4,
  },
  diagnosticsSheetCard: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    padding: 16,
    maxHeight: '80%',
  },
  diagnosticsSheetTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
  },
  diagnosticsSheetSubtitle: {
    marginTop: 6,
    marginBottom: 12,
    color: '#4b5563',
    fontSize: 14,
  },
})
