import type { Service } from 'react-native-candle'

const serviceDisplayNames: Record<Service, string> = {
  airbnb: 'Airbnb',
  aaa: 'AAA',
  american_airlines: 'American Airlines',
  american_express: 'American Express',
  amazon: 'Amazon',
  apple: 'Apple Wallet',
  avis: 'AVIS',
  bank_of_america: 'Bank of America',
  blue_bottle: 'Blue Bottle',
  cash_app: 'Cash App',
  capital_one: 'Capital One',
  charles_schwab: 'Charles Schwab',
  chipotle: 'Chipotle',
  chime: 'Chime',
  cnn: 'CNN',
  coinbase: 'Coinbase',
  costco: 'Costco',
  citibank: 'Citi',
  delta: 'Delta',
  discover: 'Discover',
  discord: 'Discord',
  doordash: 'DoorDash',
  espn: 'ESPN',
  experian: 'Experian',
  facebook: 'Facebook',
  fox: 'Fox',
  geico: 'Geico',
  getaround: 'Getaround',
  grubhub: 'Grubhub',
  hawaiian: 'Hawaiian',
  hertz: 'Hertz',
  hotels: 'Hotels',
  instagram: 'Instagram',
  jpmorgan_chase: 'JPMorgan Chase',
  jetblue: 'JetBlue',
  kalshi: 'Kalshi',
  linkedin: 'Linkedin',
  lyft: 'Lyft',
  mcdonalds: 'Mcdonalds',
  messenger: 'Messenger',
  messages: 'Messages',
  new_york_times: 'New York Times',
  netflix: 'Netflix',
  openai: 'OpenAI',
  opentable: 'OpenTable',
  paypal: 'PayPal',
  perplexity: 'Perplexity',
  pinterest: 'Pinterest',
  polymarket: 'Polymarket',
  progressive: 'Progressive',
  reddit: 'Reddit',
  resy: 'Resy',
  revel: 'Revel',
  robinhood: 'Robinhood',
  sandbox: 'Sandbox',
  signal: 'Signal',
  snapchat: 'Snapchat',
  southwest: 'Southwest',
  starbucks: 'Starbucks',
  state_farm: 'State Farm',
  sweetgreen: 'Sweetgreen',
  telegram: 'Telegram',
  tesla: 'Tesla',
  turo: 'Turo',
  uber: 'Uber',
  uber_eats: 'Uber Eats',
  united: 'United',
  vanguard: 'Vanguard',
  venmo: 'Venmo',
  wall_street_journal: 'Wall Street Journal',
  walmart: 'Walmart',
  washington_post: 'Washington Post',
  wells_fargo: 'Wells Fargo',
  waymo: 'Waymo',
  whatsapp: 'WhatsApp',
  whole_foods: 'Whole Foods',
  x: 'X (formerly Twitter)',
  yahoo: 'Yahoo',
  youtube: 'YouTube',
  zipcar: 'Zipcar',
}

export const displayService = (service: Service): string => serviceDisplayNames[service]

export const getServiceLogo = (service: Service): string =>
  `https://institution-logos.s3.us-east-1.amazonaws.com/${service}.png`
