name: preview
on: pull_request

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create .env in ./example
        run: |
          echo "CANDLE_APP_KEY=${{ secrets.CANDLE_APP_KEY }}" > example/.env
          echo "CANDLE_APP_SECRET=${{ secrets.CANDLE_APP_SECRET }}" >> example/.env

      - name: Install dependencies
        run: bun install

      - name: Check for EXPO_CLI_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_CLI_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_CLI_TOKEN }}

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --input-dir=example --auto --message "Preview update for PR #${{ github.event.pull_request.number }}"
